<robot  xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="pi_const" value="3.14159265"/>
  <xacro:property name="camera_link" value="0.2" />

  
  <joint name="camera_joint" type="fixed">
    <axis xyz="0 1 0.5" />
    <!-- <origin xyz="${camera_link} 0 ${height3 - axel_offset*2}" rpy="0 0 0"/> -->
    <origin xyz="${camera_link} 0 0.01" rpy="0 0 0"/>
    <parent link="body_link"/>
    <child link="camera_link"/>
  </joint>

  <!-- Camera -->
  <link name="camera_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.01" length="0.02"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 ${pi_const/2} 0"/>
      <geometry>
        <cylinder radius="0.01" length="0.02"/>
      </geometry>
      <material name="grey">Gazebo/Grey</material>
    </visual>

    <xacro:inertial_cylinder mass="0.1" length="0.02" radius="0.01">
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </xacro:inertial_cylinder>
  </link>
  
   <!-- camera -->
   <gazebo reference="camera_link">
    <sensor type="camera" name="camera1">
      <update_rate>30.0</update_rate>
      <camera name="head">
        <horizontal_fov>1.3962634</horizontal_fov>
        <image>          
          <width>1920</width>
          <height>1080</height>
          <format>R8G8B8</format>
          <!-- 1920*1080 = 1080P camera -->
        </image>
        <clip>
          <near>0.02</near>
          <far>300</far>
        </clip>
        <noise>
          <type>gaussian</type>
          <!-- Noise is sampled independently per pixel on each frame.
               That pixel's noise value is added to each of its color
               channels, which at that point lie in the range [0,1]. -->
          <mean>0.0</mean>
          <stddev>0.007</stddev>
        </noise>
      </camera>
      <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>30</updateRate>
        <cameraName>rrbot/camera1</cameraName>
        <imageTopicName>image_raw</imageTopicName>
        <cameraInfoTopicName>camera_info</cameraInfoTopicName>
        <frameName>camera_link</frameName>
        <hackBaseline>0.07</hackBaseline>
        <distortionK1>0.0</distortionK1>
        <distortionK2>0.0</distortionK2>
        <distortionK3>0.0</distortionK3>
        <distortionT1>0.0</distortionT1>
        <distortionT2>0.0</distortionT2>
      </plugin>
    </sensor>
  </gazebo>
</robot>